### ISSUE TITLE
An exception occurred when trying to download from Imagefap

### ISSUE THREAD

**Issue by deodaras** [regosen/gallery_get#86] opened 2021-05-16 21:21 UTC
Traceback (most recent call last):
  File "/Volumes/128GB_NEY/IMAGEFAP/gallery_get-1.8.17/gallery_get.py", line 466, in run_wrapped
    root = GalleryGet(myurl, dest or DEST_ROOT, titleAsFolder, allowGenericPlugin).run()
  File "/Volumes/128GB_NEY/IMAGEFAP/gallery_get-1.8.17/gallery_get.py", line 457, in run
    return self.queue_jobs(page, root, subtitle)
  File "/Volumes/128GB_NEY/IMAGEFAP/gallery_get-1.8.17/gallery_get.py", line 384, in queue_jobs
    links = run_match(self.plugin.redirect, page)
  File "/Volumes/128GB_NEY/IMAGEFAP/gallery_get-1.8.17/gallery_get.py", line 118, in run_match
    result = match(source)
  File "/Volumes/128GB_NEY/IMAGEFAP/gallery_get-1.8.17/gallery_plugins/plugin_imagefap.py", line 27, in redirect
    indexed_source = urlopen_text(indexed_page)
  File "/Volumes/128GB_NEY/IMAGEFAP/gallery_get-1.8.17/gallery_utils.py", line 75, in urlopen_text
    data = urlopen_safe(url)
  File "/Volumes/128GB_NEY/IMAGEFAP/gallery_get-1.8.17/gallery_utils.py", line 27, in urlopen_safe
    return urlopen(q)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 308: Permanent Redirect
Using params: ['https://www.imagefap.com/pictures/6421563/Big-cocks', '/Volumes/128GB_NEY/IMAGEFAP/gallery_get-1.8.17', False]

**Comment by regosen** [comment] 2021-05-17 00:01
This is a duplicate of issue #83, which was fixed a few months ago in the latest version of gallery_get (1.8.18).  According to your output, you're still on version 1.8.17.

Can you upgrade your version of gallery_get and try again?

**Closed** 2021-05-25 03:16 UTC
